import pytest
import asyncio
import json
from pipeline_agent.schemas.schema import DAGPlan, TaskNode, NodeState, Runtime
from pipeline_agent.engine import AsyncPipelineEngine
from pipeline_agent.tools.tools import registry, tool

# ==========================================
# 🧪 Mock Tools for Testing
# ==========================================
call_counts = {"mock_success": 0}

@pytest.fixture(autouse=True)
def reset_mocks():
    """Reset counters before each test"""
    call_counts["mock_success"] = 0
    yield

@tool(category="test", runtime=Runtime.LOCAL_CPU, description="Mock Success")
async def mock_success_tool(val: str) -> str:
    call_counts["mock_success"] += 1
    return f"Processed: {val}"

@tool(category="test", runtime=Runtime.LOCAL_CPU, description="Mock Fail")
async def mock_fail_tool(val: str) -> str:
    raise ValueError("Intentional failure for testing")

# ==========================================
# 🧪 Test Cases
# ==========================================

@pytest.mark.asyncio
async def test_exactly_once_checkpointing(tmp_path):
    """
    Test goal: Verify that the checkpoint mechanism successfully intercepts duplicate executions,
    and that files are written to the correct hash folder.
    """
    # 1. Initialize the engine and set the checkpoint directory to pytest's isolated temp area
    engine = AsyncPipelineEngine()
    engine.checkpoint_manager.base_dir = str(tmp_path / ".checkpoints")
    
    # Simulate a Plan ID generated by timestamp and SHA
    plan_id = "20260320_120000_a1b2c3d4"
    
    node = TaskNode(
        task_id="step_1",
        tool_name="mock_success_tool",
        runtime=Runtime.LOCAL_CPU.value,
        tool_inputs_json=json.dumps({"val": "hello"})
    )
    plan = DAGPlan(plan_id=plan_id, goal="test", nodes=[node])

    # --- First run: normal execution ---
    result1 = await engine.run(plan)
    assert result1.is_success == True
    assert call_counts["mock_success"] == 1
    assert result1.final_state["step_1"] == "Processed: hello"

    # Verify that the folder is created as expected
    expected_file = tmp_path / ".checkpoints" / plan_id / "state.json"
    assert expected_file.exists()

    # --- Second run: simulate agent crash and resubmit the same DAG ---
    node.state = NodeState.PENDING # Reset node state to simulate a new incoming plan
    plan2 = DAGPlan(plan_id=plan_id, goal="test", nodes=[node])
    
    result2 = await engine.run(plan2)
    assert result2.is_success == True
    
    # 🚨 Key assertion: Even after the second run, the tool call count must still be 1!
    assert call_counts["mock_success"] == 1
    # The result must be correctly restored from the checkpoint
    assert result2.final_state["step_1"] == "Processed: hello"


@pytest.mark.asyncio
async def test_safe_halting(tmp_path):
    """
    Test goal: Verify that for A -> B -> C, when B fails, C is safely marked as CANCELLED,
    and the engine does not crash.
    """
    engine = AsyncPipelineEngine()
    engine.checkpoint_manager.base_dir = str(tmp_path / ".checkpoints")
    
    plan_id = "20260320_120000_f9e8d7c6"
    
    node_a = TaskNode(
        task_id="node_a", tool_name="mock_success_tool", 
        runtime=Runtime.LOCAL_CPU.value, tool_inputs_json='{"val": "A"}', depends_on=[]
    )
    # B depends on A and will raise an error
    node_b = TaskNode(
        task_id="node_b", tool_name="mock_fail_tool", 
        runtime=Runtime.LOCAL_CPU.value, tool_inputs_json='{"val": "${node_a.output}"}', depends_on=["node_a"]
    )
    # C depends on B
    node_c = TaskNode(
        task_id="node_c", tool_name="mock_success_tool", 
        runtime=Runtime.LOCAL_CPU.value, tool_inputs_json='{"val": "${node_b.output}"}', depends_on=["node_b"]
    )
    
    plan = DAGPlan(plan_id=plan_id, goal="test_halt", nodes=[node_a, node_b, node_c])
    
    result = await engine.run(plan)
    
    # 1. The entire pipeline must fail
    assert result.is_success == False
    
    # 2. 🚨 Key assertion: State machine transitions must match expectations
    assert node_a.state == NodeState.SUCCESS
    assert node_b.state == NodeState.FAILED
    assert node_c.state == NodeState.CANCELLED_DUE_TO_UPSTREAM
    
    # 3. Ensure node_c was never executed
    assert call_counts["mock_success"] == 1 # Only node_a was executed