from enum import Enum
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field

# ==========================================
# 🏷️ Basic Definitions (Enums)
# ==========================================

class Runtime(str, Enum):
    """
    Defines the resource environment for task execution. The engine will allocate Semaphore locks based on this tag.
    """
    LOCAL_CPU = "local_cpu"
    LOCAL_GPU = "local_gpu"
    CLOUD_API = "cloud_api"
    EXTERNAL_MCP = "external_mcp"  # 🌟 Reserved for external MCP Server use

# ==========================================
# 📊 Node State Enumeration (For Tracking Execution Status)
# ==========================================

class NodeState(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    CANCELLED_DUE_TO_UPSTREAM = "CANCELLED_DUE_TO_UPSTREAM"

# ==========================================
# 🏗️ Core Data Models (Models for LLM Generation)
# ==========================================
# ⚠️ Note: These models will be passed to OpenAI's Structured Outputs,
# so types must remain simple and clear. Avoid using overly complex Unions.

class TaskNode(BaseModel):
    """
    A single task node in the DAG.
    """
    task_id: str = Field(..., description="Unique task identifier, e.g., 'fetch_web_01'")
    tool_name: str = Field(..., description="Name of the tool to invoke")
    runtime: str = Field(..., description="Type of runtime resource required for this task, e.g., 'local_cpu', 'external_mcp'")
    state: NodeState = Field(default=NodeState.PENDING, description="Current execution state of the node")
    tool_inputs_json: str = Field(
        ..., 
        description="Input parameters for the tool (must be a JSON-formatted string). Supports ${task_id.output} syntax to reference outputs from previous tasks"
    )
    depends_on: List[str] = Field(
        default_factory=list, 
        description="List of preceding task_ids that this node depends on"
    )
    start_time: Optional[float] = None
    end_time: Optional[float] = None

class DAGPlan(BaseModel):
    """
    Complete execution plan blueprint generated by the brain.
    """
    plan_id: str = Field(..., description="Unique tracking ID for the plan")
    goal: str = Field(..., description="Original task goal description")
    nodes: List[TaskNode] = Field(..., description="List of all task nodes")


# ==========================================
# ⚙️ Execution Result Models (Execution Results for Developers)
# ==========================================

class EngineResult(BaseModel):
    """
    Standardized result object returned to developers after engine execution.
    Replaces the previously hard-to-read tuple return values.
    """
    is_success: bool = Field(..., description="Whether the process was executed completely and successfully")
    final_state: Dict[str, Any] = Field(
        default_factory=dict, 
        description="Output results of all successful nodes {task_id: output}"
    )
    failed_tasks: Dict[str, str] = Field(
        default_factory=dict,
        description="Error messages for failed nodes {task_id: error_message}"
    )